# Generated by Django 2.2.4 on 2019-11-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchmaid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmaid',
            name='maid_photo',
            field=models.ImageField(null=True, upload_to='images/maidphoto'),
        ),
    ]
