# Generated by Django 2.2.4 on 2019-11-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchmaid', '0002_searchmaid_maid_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmaid',
            name='maid_photo',
            field=models.ImageField(default=None, upload_to='images/maidphoto'),
        ),
    ]
