# Generated by Django 2.2.7 on 2019-12-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0003_auto_20191203_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='plan',
        ),
    ]
