# Generated by Django 2.2.7 on 2019-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0004_auto_20191203_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(choices=[(200, 'Basic ($200)'), (260, 'Standard ($260)'), (500, 'Premium ($500)')], default=200),
        ),
    ]
