# Generated by Django 2.2.7 on 2019-12-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0004_auto_20191203_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='name',
            field=models.IntegerField(choices=[(200, 'Basic'), (260, 'Standard'), (500, 'Premium')], default='Basic', max_length=50),
        ),
    ]
