# Generated by Django 2.2.7 on 2019-12-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0005_subplan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(choices=[('Basic ($200)', 200), ('Standard ($260)', 260), ('Premium ($500)', 500)], default=200),
        ),
    ]
