# Generated by Django 2.2.7 on 2019-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0006_auto_20191203_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(choices=[(200, 'Basic'), (260, 'Standard'), (500, 'Premium')], default=200),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Basic', max_length=50),
        ),
    ]
