# Generated by Django 2.2.7 on 2019-12-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0007_auto_20191212_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(choices=[(200, 200), (260, 260), (500, 500)], default=200),
        ),
    ]
