# Generated by Django 2.2.7 on 2019-12-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0008_auto_20191212_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplan',
            name='price',
        ),
    ]
