# Generated by Django 2.2.7 on 2019-12-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0009_remove_subplan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplan',
            name='name',
        ),
        migrations.AddField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(choices=[(200, 'Basic ($200)'), (260, 'Standard ($260)'), (500, 'Premium ($500)')], default=200),
        ),
    ]
