# Generated by Django 2.2.7 on 2019-12-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0010_auto_20191212_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Basic', max_length=50),
        ),
    ]
