# Generated by Django 2.2.7 on 2019-12-03 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191128_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agency_name', models.CharField(max_length=100, null=True)),
                ('agency_license', models.CharField(max_length=20, null=True)),
                ('office_no', models.CharField(max_length=20, null=True)),
                ('office_address', models.CharField(max_length=100, null=True)),
                ('handphone_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50, null=True)),
                ('handphone_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='agency_license',
        ),
        migrations.RemoveField(
            model_name='user',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='handphone_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='office_no',
        ),
    ]
