# Generated by Django 2.2.7 on 2019-12-03 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisted_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedmaid',
            name='maid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Maid'),
        ),
    ]
