# Generated by Django 2.2.7 on 2019-12-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisted_cart', '0002_auto_20191203_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedmaid',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer'),
        ),
    ]
