# Generated by Django 2.2.7 on 2019-11-29 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webfront', '0002_auto_20191128_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='maid',
            name='agency_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maid',
            name='language_ability',
            field=models.CharField(choices=[('English', 'English'), ('Mandarin/ Chinese Dialect', 'Mandarin/ Chinese Dialect'), ('Bahasa Indonesia', 'Bahasa Indonesia'), ('Hindi/ Tamil', 'Hindi/ Tamil'), ('Burmese', 'Burmese'), ('No Preference', 'No Preference')], default='No Preference', max_length=50),
        ),
        migrations.AddField(
            model_name='maid',
            name='main_responsibility',
            field=models.CharField(choices=[('Cooking', 'Cooking'), ('Care for Children', 'Care for Children'), ('Care for Elderly', 'Care for Elderly'), ('Care for Disabled', 'Care for Disabled'), ('General Housework', 'General Housework'), ('No Preference', 'No Preference')], default='No Preference', max_length=50),
        ),
        migrations.AlterField(
            model_name='maid',
            name='age',
            field=models.CharField(choices=[('23 to 25', '23 to 25'), ('26 to 30', '26 to 30'), ('31 to 35', '31 to 35'), ('36 to 40', '36 to 40'), ('41 to 50', '41 to 50'), ('No Preference', 'No Preference')], default='No Preference', max_length=50),
        ),
        migrations.AlterField(
            model_name='maid',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divoreced'), ('No Preference', 'No Preference')], default='No Preference', max_length=50),
        ),
        migrations.AlterField(
            model_name='maid',
            name='nationality',
            field=models.CharField(choices=[('Filipino', 'Filipino'), ('Indonesian', 'Indonesian'), ('Indian', 'Indian'), ('Myanmarese', 'Myanmarese'), ('Others', 'Others'), ('No Preference', 'No Preference')], default='No Preference', max_length=50),
        ),
        migrations.AlterField(
            model_name='maid',
            name='type_of_maid',
            field=models.CharField(choices=[('New', 'New'), ('Transfer', 'Transfer'), ('Experience', 'Experience'), ('No Preference', 'No Preference')], default='No Preference', max_length=50),
        ),
    ]
