# Generated by Django 2.2.7 on 2019-12-03 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nationality', models.CharField(choices=[('Filipino', 'Filipino'), ('Indonesian', 'Indonesian'), ('Indian', 'Indian'), ('Myanmarese', 'Myanmarese'), ('Others', 'Others'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('type_of_maid', models.CharField(choices=[('New', 'New'), ('Transfer', 'Transfer'), ('Experience', 'Experience'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('main_responsibility', models.CharField(choices=[('Cooking', 'Cooking'), ('Care for Children', 'Care for Children'), ('Care for Elderly', 'Care for Elderly'), ('Care for Disabled', 'Care for Disabled'), ('General Housework', 'General Housework'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('language_ability', models.CharField(choices=[('English', 'English'), ('Mandarin/ Chinese Dialect', 'Mandarin/ Chinese Dialect'), ('Bahasa Indonesia', 'Bahasa Indonesia'), ('Hindi/ Tamil', 'Hindi/ Tamil'), ('Burmese', 'Burmese'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('age', models.CharField(choices=[('23 to 25', '23 to 25'), ('26 to 30', '26 to 30'), ('31 to 35', '31 to 35'), ('36 to 40', '36 to 40'), ('41 to 50', '41 to 50'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divoreced'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('agency_name', models.CharField(max_length=50)),
                ('maid_photo', models.ImageField(default=None, upload_to='images/maidphoto')),
                ('agency_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
