# Generated by Django 2.2.7 on 2019-12-05 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191203_0758'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maid',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maid',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='maid',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ('College', 'College'), ('Degree', 'Degree'), ('Others', 'Others')], default='Others', max_length=50),
        ),
        migrations.AddField(
            model_name='maid',
            name='employment_history',
            field=models.TextField(default='Haha'),
        ),
        migrations.AddField(
            model_name='maid',
            name='no_of_children',
            field=models.CharField(choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('more than 3', 'more than 3')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='maid',
            name='religion',
            field=models.CharField(choices=[('None', 'None'), ('Buddhist', 'Buddhist'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian/ Catholic', 'Christian/ Catholic'), ('Others', 'Others')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='maid',
            name='salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='maid',
            name='agency_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Agency'),
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer')),
                ('maid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.Maid')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('nationality', models.CharField(choices=[('Filipino', 'Filipino'), ('Indonesian', 'Indonesian'), ('Indian', 'Indian'), ('Myanmarese', 'Myanmarese'), ('Others', 'Others'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('main_responsibility', models.CharField(choices=[('Cooking', 'Cooking'), ('Care for Children', 'Care for Children'), ('Care for Elderly', 'Care for Elderly'), ('Care for Disabled', 'Care for Disabled'), ('General Housework', 'General Housework'), ('No Preference', 'No Preference')], default='No Preference', max_length=50)),
                ('employer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employer')),
            ],
        ),
    ]
