# Generated by Django 2.2.7 on 2019-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20191205_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='employer',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.CharField(default='nil', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='name',
            field=models.CharField(default='nil', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phonenumber',
            field=models.CharField(default='nil', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortlist',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='maid',
            name='employment_history',
            field=models.TextField(default=''),
        ),
    ]
