# Generated by Django 2.2.7 on 2019-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20191206_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='agency',
            field=models.CharField(default='agency123', max_length=50),
            preserve_default=False,
        ),
    ]
