# Generated by Django 2.2.7 on 2019-12-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_shortlist_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='enquiry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
