# Generated by Django 2.2.7 on 2019-12-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20191206_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='enquiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
