# Generated by Django 2.2.7 on 2019-12-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20191206_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlist',
            old_name='enquiry_date',
            new_name='shortlist_date',
        ),
    ]
